# Imprting Libraries

In [54]:
import numpy as np 

# Decision Matrix

In [55]:
decision_matrix = np.array([
    [9, 7, 1, 2],
    [11, 3, 5, 7],
    [6, 5, 4, 6],
    [8, 9, 3, 7],
    [8, 10, 7, 3],
    [7, 9, 4, 5],
])

print("Decision Matrix = ")
decision_matrix

Decision Matrix = 


array([[ 9,  7,  1,  2],
       [11,  3,  5,  7],
       [ 6,  5,  4,  6],
       [ 8,  9,  3,  7],
       [ 8, 10,  7,  3],
       [ 7,  9,  4,  5]])

# Criteria Weights

In [56]:
weights = np.array([0.4, 0.3, 0.1, 0.2])

print("Weights = ",weights)

Weights =  [0.4 0.3 0.1 0.2]


# Normalize Decision Matrix

In [57]:
normalized_matrix = decision_matrix / np.sqrt((decision_matrix ** 2).sum(axis = 0))

print("Normalize Decision Matrix = ",normalized_matrix)

Normalize Decision Matrix =  [[0.44179262 0.37686733 0.09284767 0.15249857]
 [0.53996876 0.16151457 0.46423835 0.533745  ]
 [0.29452842 0.26919095 0.37139068 0.45749571]
 [0.39270455 0.48454371 0.27854301 0.533745  ]
 [0.39270455 0.5383819  0.64993368 0.22874786]
 [0.34361649 0.48454371 0.37139068 0.38124643]]


# Weighted Normal Matrix

In [58]:
weighted_normal_matrix = normalized_matrix * weights

print("Weighted Normal Matrix = ",weighted_normal_matrix)

Weighted Normal Matrix =  [[0.17671705 0.1130602  0.00928477 0.03049971]
 [0.21598751 0.04845437 0.04642383 0.106749  ]
 [0.11781137 0.08075729 0.03713907 0.09149914]
 [0.15708182 0.14536311 0.0278543  0.106749  ]
 [0.15708182 0.16151457 0.06499337 0.04574957]
 [0.13744659 0.14536311 0.03713907 0.07624929]]


# Determine Ideal Solution and Negative ideal solution

In [59]:
ideal_solution = np.array([weighted_normal_matrix[:,i].max() if weights[i] > 0 else weighted_normal_matrix[:,i].min() for i in range(len(weights))])

print("Ideal_Solution = " ,ideal_solution) 

negative_Ideal_Solution = np.array([weighted_normal_matrix[:,i].min() if weights[i] > 0 else weighted_normal_matrix[:,i].max() for i in range(len(weights))])

print("Negative_Ideal_Solution = " ,negative_Ideal_Solution) 

Ideal_Solution =  [0.21598751 0.16151457 0.06499337 0.106749  ]
Negative_Ideal_Solution =  [0.11781137 0.04845437 0.00928477 0.03049971]


# Calculate the sepration Distance

In [60]:
eucledian_distance_ideal = np.sqrt(((weighted_normal_matrix - ideal_solution) ** 2).sum(axis = 1))

print("Eucledian_Distance_Ideal_Solution = " ,eucledian_distance_ideal) 

negative_eucledian_distance_ideal = np.sqrt(((weighted_normal_matrix - negative_Ideal_Solution) ** 2).sum(axis = 1))

print("Negative_Eucledian_Distance_Ideal_Solution = " ,negative_eucledian_distance_ideal) 

Eucledian_Distance_Ideal_Solution =  [0.11316977 0.11457502 0.13102944 0.07148468 0.08479864 0.09019778]
Negative_Eucledian_Distance_Ideal_Solution =  [0.08742879 0.1297375  0.07443299 0.13073735 0.13289388 0.11245324]


# Calculate relative closeness to Ideal Solution 

In [61]:
closeness_coefficients = eucledian_distance_ideal / (eucledian_distance_ideal + negative_eucledian_distance_ideal)

print("Closeness_Coefficients= " ,closeness_coefficients)

Closeness_Coefficients=  [0.56416044 0.46896911 0.63772942 0.35349601 0.38953401 0.44508918]


# Determine the best alternative

In [62]:
best_alternative = np.argmax(closeness_coefficients)

print("Best Alternative = " ,best_alternative)

Best Alternative =  2
